### ISSUE TITLE
case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by stevenroose** [kisonecat/pdiff#1]
```
go get github.com/kisonecat/pdiff
can't load package: package github.com/kisonecat/pdiff: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

I explicitly removed the `$GOPATH/src/github.com/Sirupsen` and `$GOPATH/src/github.com/sirupsen` directory and the issue persists. This might be because one of your dependencies also imports logrus with a different casing.

**Comment by kisonecat** [comment]
Good catch.  https://github.com/kisonecat/pdiff/commit/924310d8e7153961f682afbac8ff933b3132f292 should resolve this.
